---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  # namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moop
      service: audit-service
  template:
    metadata:
      labels:
        app: moop
        service: audit-service
    spec:
      serviceAccountName: moop

      containers:
      - name: moop-audit-service
        image: registry.datadynamic.io/moop/moop-audit-service:{IMAGE_TAG_for_change}
        volumeMounts:
        - name:  audit-service-config
          mountPath: /app/config.yaml
          subPath: config.yaml

        resources: {}
          # requests:
          #   memory: 32Mi
          #   cpu: 40m
          # limits:
          #   memory: 2Gi
          #   cpu: 1


      imagePullSecrets:
      - name: regcred

      volumes:
      - name:  audit-service-config
        configMap:
          name: audit-service-config
