---
apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  ports:
  - name: es-service-http
    nodePort: 31786
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moop
    service: es-service
  type: NodePort
